config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users, :controllers => { :invitations => 'users/invitations' }
  devise_scope :user do
    get "users/company-sign-up", to: "users/registrations#new_company", as: :new_company
    post "users/company-sign-up", to: "users/registrations#create_company", as: :create_company
    get "business/users/new", to: "users/invitations#new", as: :custom_new_user_invitation
    post "business/users", to: "users/invitations#create", as: :custom_create_user_invitation
  end

  namespace :business do
    get "dashboard", to: "dashboard#show", as: :dashboard
    resources :users, only: [:index, :destroy] do
        post "toggle_role", on: :member
    end
    namespace :settings do
      get "hours", to: "settings#hours", as: :hours
      put "hours", to: "settings#save_hours", as: :hours_save
    end
    resources :items, only: [:index, :show, :new, :create]
    resources :item_categories, only: [:index, :show, :new, :create]
  end
end

app/controllers/business/settings/settings_controller.rb
module Business
  module Settings
    class SettingsController < ApplicationController
      before_action :authenticate_user!
      before_action :redirect_if_not_business_partner

      def hours
        @company = current_user.company
        if @company.business_hours.count == 0
          7.times do |day|
            @company.business_hours.build(company: @company, day: day)
          end
        end
      end

      def save_hours
        @company = current_user.company
        binding.pry
      end

      private

      def hours_params
        params.require(:company).permit(business_hours_attributes: [:id, :open, :close, :day])
      end
    end
  end
end

app/views/business/settings/settings/hours.html.haml
%h2 Business hours settings for #{@company.name}.

#settings-hours-accordion.panel-group{"aria-multiselectable" => "true", :role => "tablist"}
  .panel.panel-default
    #headingOne.panel-heading{:role => "tab"}
      %h4.panel-title
        %a{"aria-controls" => "hours-every-day", "aria-expanded" => "true", "data-parent" => "#settings-hours-accordion", "data-toggle" => "collapse", :href => "#hours-every-day"}
          Set one range for each day
    #hours-every-day.panel-collapse.collapse.in{"aria-labelledby" => "headingOne", :role => "tabpanel"}
      .panel-body
        = simple_form_for(@company, url: business_settings_hours_save_path) do |f|
          = f.simple_fields_for :business_hours do |c|
            %h3 #{c.object.day}
            .form-group
              = c.input_field :open, label: false, required: true
              = c.input_field :close, label: false, required: true
              = c.hidden_field :day
              = c.hidden_field :id
          = f.button :submit, 'Save', class: 'btn btn-default'

  .panel.panel-default
    #headingTwo.panel-heading{:role => "tab"}
      %h4.panel-title
        %a.collapsed{"aria-controls" => "hours-weekgroups", "aria-expanded" => "false", "data-parent" => "#settings-hours-accordion", "data-toggle" => "collapse", :href => "#hours-weekgroups"}
          Set for weekday and weekend seperately
    #hours-weekgroups.panel-collapse.collapse{"aria-labelledby" => "headingTwo", :role => "tabpanel"}
      .panel-body

  .panel.panel-default
    #headingThree.panel-heading{:role => "tab"}
      %h4.panel-title
        %a.collapsed{"aria-controls" => "hours-seperate", "aria-expanded" => "false", "data-parent" => "#settings-hours-accordion", "data-toggle" => "collapse", :href => "#hours-seperate"}
          Set for each day seperately
    #hours-seperate.panel-collapse.collapse{"aria-labelledby" => "headingThree", :role => "tabpanel"}
      .panel-body