config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users, :controllers => { :invitations => 'users/invitations' }
  devise_scope :user do
    get "users/company-sign-up", to: "users/registrations#new_company", as: :new_company
    post "users/company-sign-up", to: "users/registrations#create_company", as: :create_company
    get "business/users/new", to: "users/invitations#new", as: :custom_new_user_invitation
    post "business/users", to: "users/invitations#create", as: :custom_create_user_invitation
  end

  namespace :business do
    get "dashboard", to: "dashboard#show", as: :dashboard
    resources :users, only: [:index, :destroy] do
        post "toggle_role", on: :member
    end
    namespace :settings do
      get "hours", to: "settings#hours", as: :hours
      put "hours", to: "settings#save_hours", as: :hours_save
    end
    resources :items, only: [:index, :show, :new, :create]
    resources :item_categories, only: [:index, :show, :new, :create]
  end
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
- if current_user
  %li
    = link_to 'Sign out', destroy_user_session_path, method: :delete
  %li
    = link_to 'Your account', edit_user_registration_path
- else
  %li
    = link_to 'Sign up', new_user_registration_path
  %li
    = link_to 'Become business partner', new_company_path

- if current_user && current_user.business_partner?
  %li
    = link_to 'Business', business_dashboard_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Wypozyczalnia'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Wypozyczalnia'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      .container
        = render 'layouts/messages'
        = yield